In [75]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris 

In [76]:
data = load_iris()
df = pd.DataFrame(data["data"])
df.columns = data.feature_names
df['target'] = data.target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [77]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [78]:
from sklearn.model_selection import train_test_split as tts
X_train, X_test, y_train,y_test = tts(X,y,test_size = 0.2)
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
141                6.9               3.1                5.1               2.3
29                 4.7               3.2                1.6               0.2
118                7.7               2.6                6.9               2.3
124                6.7               3.3                5.7               2.1
51                 6.4               3.2                4.5               1.5
..                 ...               ...                ...               ...
13                 4.3               3.0                1.1               0.1
43                 5.0               3.5                1.6               0.6
87                 6.3               2.3                4.4               1.3
57                 4.9               2.4                3.3               1.0
144                6.7               3.3                5.7               2.5

[120 rows x 4 columns]

In [79]:
from sklearn.model_selection import StratifiedKFold
sf = StratifiedKFold(n_splits = 5, shuffle = True, random_state = 42)

In [80]:
sf.get_n_splits(X_train, y_train)

5

In [81]:
sf_=sf.split(X_train, y_train)
ct=0
for i in sf_:
    print(i)
    ct+=1
    print("End",ct)

(array([  0,   2,   3,   4,   5,   6,   7,   8,   9,  11,  12,  14,  15,
        17,  19,  20,  21,  22,  24,  25,  26,  27,  28,  31,  32,  33,
        34,  35,  36,  37,  38,  39,  40,  42,  43,  44,  45,  47,  48,
        49,  50,  51,  52,  53,  56,  57,  58,  59,  60,  61,  62,  64,
        65,  66,  68,  69,  70,  71,  72,  74,  75,  76,  78,  80,  81,
        83,  84,  85,  86,  87,  89,  90,  91,  92,  95,  96,  97,  98,
        99, 100, 101, 102, 103, 104, 105, 106, 108, 110, 111, 112, 114,
       115, 116, 117, 118, 119]), array([  1,  10,  13,  16,  18,  23,  29,  30,  41,  46,  54,  55,  63,
        67,  73,  77,  79,  82,  88,  93,  94, 107, 109, 113]))
End 1
(array([  0,   1,   2,   4,   5,   7,   8,   9,  10,  12,  13,  14,  15,
        16,  17,  18,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
        30,  31,  32,  37,  38,  39,  40,  41,  45,  46,  47,  48,  49,
        51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  63,  64,
        65,  66,  67,  69,  71

In [82]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)
y_train_pred = dt.predict(X_train) 
y_test_pred = dt.predict(X_test)

In [83]:
# lst_accu_stratified = []
# for train_index, test_index in sf.split(X, y):
#     x_train_fold, x_test_fold = X[train_index], X[test_index]
#     y_train_fold, y_test_fold = y[train_index], y[test_index]
#     dt.fit(x_train_fold, y_train_fold)
#     lst_accu_stratified.append(dt.score(x_test_fold, y_test_fold))

In [84]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_train,y_train_pred))
print(accuracy_score(y_test,y_test_pred))
print(confusion_matrix(y_train,y_train_pred))
print(confusion_matrix(y_test,y_test_pred))

1.0
0.9666666666666667
[[38  0  0]
 [ 0 42  0]
 [ 0  0 40]]
[[12  0  0]
 [ 0  8  0]
 [ 0  1  9]]


In [ ]:
import pickle
with open('model.pkl','wb') as file:
    pickle.dump(dt, file)